spring.application.name=kh-completion-api

spring.datasource.url=jdbc:postgresql://localhost:5432/kh_completion
spring.datasource.username=${DB_USERNAME:kh_user}
spring.datasource.password=${DB_PASSWORD:kh_password}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration