CREATE TABLE worlds
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name      VARCHAR(120) NOT NULL,
    game      VARCHAR(60)  NOT NULL,
    image_url VARCHAR(500),

    CONSTRAINT pk_worlds PRIMARY KEY (id)
);