CREATE TABLE items
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name      VARCHAR(120) NOT NULL,
    image_url VARCHAR(500),

    CONSTRAINT pk_items PRIMARY KEY (id)
);

CREATE TABLE chests
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    location VARCHAR(100) NOT NULL,
    world_id BIGINT       NOT NULL,
    item_id  BIGINT       NOT NULL,

    CONSTRAINT pk_chests PRIMARY KEY (id),
    CONSTRAINT fk_chests_world
        FOREIGN KEY (world_id) REFERENCES worlds (id),
    CONSTRAINT fk_chests_item
        FOREIGN KEY (item_id) REFERENCES items (id)
);