-- Kingdom Hearts II Final Mix
-- 95 itens e 301 baus registrados no Diario do Grilo.
-- Os 14 baus do prologo do Roxas nao estao incluidos, pois nao fazem parte do diario.
-- As imagens usam um placeholder

INSERT INTO items (name, image_url)
VALUES
    ('100 Acre Wood Map', '/images/items/placeholder.webp'),
    ('AP Boost', '/images/items/placeholder.webp'),
    ('Basement Map', '/images/items/placeholder.webp'),
    ('Blazing Shard', '/images/items/placeholder.webp'),
    ('Blazing Stone', '/images/items/placeholder.webp'),
    ('Bright Shard', '/images/items/placeholder.webp'),
    ('Bright Stone', '/images/items/placeholder.webp'),
    ('Castle Map', '/images/items/placeholder.webp'),
    ('Castle Perimeter Map', '/images/items/placeholder.webp'),
    ('Cave of Wonders Map', '/images/items/placeholder.webp'),
    ('Caverns Map', '/images/items/placeholder.webp'),
    ('Central Computer Core Map', '/images/items/placeholder.webp'),
    ('Christmas Town Map', '/images/items/placeholder.webp'),
    ('Cornerstone Hill Map', '/images/items/placeholder.webp'),
    ('Cosmic Arts', '/images/items/placeholder.webp'),
    ('Cosmic Belt', '/images/items/placeholder.webp'),
    ('Cosmic Chain', '/images/items/placeholder.webp'),
    ('Cosmic Ring', '/images/items/placeholder.webp'),
    ('Dark City Map', '/images/items/placeholder.webp'),
    ('Dark Crystal', '/images/items/placeholder.webp'),
    ('Dark Gem', '/images/items/placeholder.webp'),
    ('Dark Remembrance Map', '/images/items/placeholder.webp'),
    ('Dark Shard', '/images/items/placeholder.webp'),
    ('Dark Stone', '/images/items/placeholder.webp'),
    ('Defense Boost', '/images/items/placeholder.webp'),
    ('Depths of Remembrance Map', '/images/items/placeholder.webp'),
    ('Draw Ring', '/images/items/placeholder.webp'),
    ('Drive Recovery', '/images/items/placeholder.webp'),
    ('Energy Crystal', '/images/items/placeholder.webp'),
    ('Energy Shard', '/images/items/placeholder.webp'),
    ('Energy Stone', '/images/items/placeholder.webp'),
    ('Ether', '/images/items/placeholder.webp'),
    ('Feather Charm', '/images/items/placeholder.webp'),
    ('Frost Crystal', '/images/items/placeholder.webp'),
    ('Frost Gem', '/images/items/placeholder.webp'),
    ('Frost Shard', '/images/items/placeholder.webp'),
    ('Frost Stone', '/images/items/placeholder.webp'),
    ('Gaia Belt', '/images/items/placeholder.webp'),
    ('Garden of Assemblage Map', '/images/items/placeholder.webp'),
    ('Guard Recipe', '/images/items/placeholder.webp'),
    ('Gull Wing', '/images/items/placeholder.webp'),
    ('Halloween Town Map', '/images/items/placeholder.webp'),
    ('Hi-Potion', '/images/items/placeholder.webp'),
    ('I/O Tower Map', '/images/items/placeholder.webp'),
    ('King Recipe', '/images/items/placeholder.webp'),
    ('Lightning Shard', '/images/items/placeholder.webp'),
    ('Lightning Stone', '/images/items/placeholder.webp'),
    ('Lost Illusion', '/images/items/placeholder.webp'),
    ('Lucid Gem', '/images/items/placeholder.webp'),
    ('Lucid Shard', '/images/items/placeholder.webp'),
    ('Lucid Stone', '/images/items/placeholder.webp'),
    ('Magic Boost', '/images/items/placeholder.webp'),
    ('Manifest Illusion', '/images/items/placeholder.webp'),
    ('Mega Recipe', '/images/items/placeholder.webp'),
    ('Mega-Potion', '/images/items/placeholder.webp'),
    ('Meteor Staff', '/images/items/placeholder.webp'),
    ('Moon Recipe', '/images/items/placeholder.webp'),
    ('Mythril Crystal', '/images/items/placeholder.webp'),
    ('Mythril Gem', '/images/items/placeholder.webp'),
    ('Mythril Shard', '/images/items/placeholder.webp'),
    ('Mythril Stone', '/images/items/placeholder.webp'),
    ('Naval Map', '/images/items/placeholder.webp'),
    ('Non-Existent Proof', '/images/items/placeholder.webp'),
    ('Oasis Map', '/images/items/placeholder.webp'),
    ('Ogre Shield', '/images/items/placeholder.webp'),
    ('Orichalcum', '/images/items/placeholder.webp'),
    ('Orichalcum+', '/images/items/placeholder.webp'),
    ('Palace Map', '/images/items/placeholder.webp'),
    ('Pit Cell Map', '/images/items/placeholder.webp'),
    ('Potion', '/images/items/placeholder.webp'),
    ('Power Boost', '/images/items/placeholder.webp'),
    ('Power Crystal', '/images/items/placeholder.webp'),
    ('Power Shard', '/images/items/placeholder.webp'),
    ('Power Stone', '/images/items/placeholder.webp'),
    ('Pride Rock Map', '/images/items/placeholder.webp'),
    ('Queen Recipe', '/images/items/placeholder.webp'),
    ('Recovery Recipe', '/images/items/placeholder.webp'),
    ('Remembrance Crystal', '/images/items/placeholder.webp'),
    ('Remembrance Gem', '/images/items/placeholder.webp'),
    ('Ruins Map', '/images/items/placeholder.webp'),
    ('Savannah Map', '/images/items/placeholder.webp'),
    ('Serenity Crystal', '/images/items/placeholder.webp'),
    ('Serenity Gem', '/images/items/placeholder.webp'),
    ('Serenity Shard', '/images/items/placeholder.webp'),
    ('Skill Recipe', '/images/items/placeholder.webp'),
    ('Skill Ring', '/images/items/placeholder.webp'),
    ('Star Recipe', '/images/items/placeholder.webp'),
    ('Style Recipe', '/images/items/placeholder.webp'),
    ('Tent', '/images/items/placeholder.webp'),
    ('The Great Maw Map', '/images/items/placeholder.webp'),
    ('Torn Pages', '/images/items/placeholder.webp'),
    ('Tower Map', '/images/items/placeholder.webp'),
    ('Ukulele Charm', '/images/items/placeholder.webp'),
    ('Ultima Recipe', '/images/items/placeholder.webp'),
    ('Underworld Map', '/images/items/placeholder.webp');

WITH chest_data (world_name, location, item_name) AS
         (
             VALUES
                 ('Twilight Town', 'The Old Mansion', 'Potion'),
                 ('Twilight Town', 'The Old Mansion', 'Mythril Shard'),
                 ('Twilight Town', 'The Woods', 'Potion'),
                 ('Twilight Town', 'The Woods', 'Mythril Shard'),
                 ('Twilight Town', 'The Woods', 'Hi-Potion'),
                 ('Twilight Town', 'Tram Common', 'Hi-Potion'),
                 ('Twilight Town', 'Tram Common', 'AP Boost'),
                 ('Twilight Town', 'Tram Common', 'Tent'),
                 ('Twilight Town', 'Tram Common', 'Mythril Shard'),
                 ('Twilight Town', 'Tram Common', 'Potion'),
                 ('Twilight Town', 'Tram Common', 'Mythril Shard'),
                 ('Twilight Town', 'Tram Common', 'Potion'),
                 ('Twilight Town', 'Central Station', 'Tent'),
                 ('Twilight Town', 'Central Station', 'Hi-Potion'),
                 ('Twilight Town', 'Central Station', 'Mythril Shard'),
                 ('Twilight Town', 'Underground Concourse', 'Mythril Gem'),
                 ('Twilight Town', 'Underground Concourse', 'Orichalcum'),
                 ('Twilight Town', 'Underground Concourse', 'AP Boost'),
                 ('Twilight Town', 'Underground Concourse', 'Mythril Crystal'),
                 ('Twilight Town', 'Tunnelway', 'Orichalcum'),
                 ('Twilight Town', 'Tunnelway', 'Mythril Crystal'),
                 ('Twilight Town', 'Sunset Terrace', 'Orichalcum+'),
                 ('Twilight Town', 'Sunset Terrace', 'Mythril Shard'),
                 ('Twilight Town', 'Sunset Terrace', 'Mythril Crystal'),
                 ('Twilight Town', 'Sunset Terrace', 'AP Boost'),
                 ('Twilight Town', 'Mansion Foyer', 'Mythril Crystal'),
                 ('Twilight Town', 'Mansion Foyer', 'Mythril Stone'),
                 ('Twilight Town', 'Mansion Foyer', 'Serenity Crystal'),
                 ('Twilight Town', 'Mansion: Dining Room', 'Mythril Crystal'),
                 ('Twilight Town', 'Mansion: Dining Room', 'Mythril Stone'),
                 ('Twilight Town', 'Mansion: Library', 'Orichalcum'),
                 ('Twilight Town', 'Mansion: Basement Corridor', 'Ultima Recipe'),
                 ('The Mysterious Tower', 'The Tower', 'Potion'),
                 ('The Mysterious Tower', 'The Tower', 'Hi-Potion'),
                 ('The Mysterious Tower', 'The Tower', 'Ether'),
                 ('The Mysterious Tower', 'The Tower: Entryway', 'Ether'),
                 ('The Mysterious Tower', 'The Tower: Entryway', 'Mythril Shard'),
                 ('The Mysterious Tower', 'The Tower: Sorcerer''s Loft', 'Tower Map'),
                 ('The Mysterious Tower', 'The Tower: Sorcerer''s Wardrobe', 'Mythril Stone'),
                 ('Hollow Bastion / Radiant Garden', 'Borough', 'Drive Recovery'),
                 ('Hollow Bastion / Radiant Garden', 'Borough', 'AP Boost'),
                 ('Hollow Bastion / Radiant Garden', 'Borough', 'Hi-Potion'),
                 ('Hollow Bastion / Radiant Garden', 'Borough', 'Mythril Shard'),
                 ('Hollow Bastion / Radiant Garden', 'Borough', 'Dark Shard'),
                 ('Hollow Bastion / Radiant Garden', 'Postern', 'Castle Perimeter Map'),
                 ('Hollow Bastion / Radiant Garden', 'Postern', 'Mythril Gem'),
                 ('Hollow Bastion / Radiant Garden', 'Postern', 'AP Boost'),
                 ('Hollow Bastion / Radiant Garden', 'Corridors', 'Mythril Stone'),
                 ('Hollow Bastion / Radiant Garden', 'Corridors', 'Mythril Crystal'),
                 ('Hollow Bastion / Radiant Garden', 'Corridors', 'Dark Crystal'),
                 ('Hollow Bastion / Radiant Garden', 'Corridors', 'AP Boost'),
                 ('Hollow Bastion / Radiant Garden', 'Ansem''s Study', 'Skill Recipe'),
                 ('Hollow Bastion / Radiant Garden', 'Ansem''s Study', 'Ukulele Charm'),
                 ('Hollow Bastion / Radiant Garden', 'Restoration Site', 'Moon Recipe'),
                 ('Hollow Bastion / Radiant Garden', 'Restoration Site', 'AP Boost'),
                 ('Hollow Bastion / Radiant Garden', 'Crystal Fissure', 'Torn Pages'),
                 ('Hollow Bastion / Radiant Garden', 'Crystal Fissure', 'The Great Maw Map'),
                 ('Hollow Bastion / Radiant Garden', 'Crystal Fissure', 'Energy Crystal'),
                 ('Hollow Bastion / Radiant Garden', 'Crystal Fissure', 'AP Boost'),
                 ('Hollow Bastion / Radiant Garden', 'Postern', 'Gull Wing'),
                 ('Hollow Bastion / Radiant Garden', 'Heartless Manufactory', 'Cosmic Chain'),
                 ('Hollow Bastion / Radiant Garden', 'Cavern of Remembrance: Depths', 'AP Boost'),
                 ('Hollow Bastion / Radiant Garden', 'Cavern of Remembrance: Depths', 'Power Crystal'),
                 ('Hollow Bastion / Radiant Garden', 'Cavern of Remembrance: Depths', 'Frost Crystal'),
                 ('Hollow Bastion / Radiant Garden', 'Cavern of Remembrance: Depths', 'Manifest Illusion'),
                 ('Hollow Bastion / Radiant Garden', 'Cavern of Remembrance: Depths', 'AP Boost'),
                 ('Hollow Bastion / Radiant Garden', 'Cavern of Remembrance: Depths', 'Remembrance Gem'),
                 ('Hollow Bastion / Radiant Garden', 'Cavern of Remembrance: Mining Area', 'Serenity Gem'),
                 ('Hollow Bastion / Radiant Garden', 'Cavern of Remembrance: Mining Area', 'AP Boost'),
                 ('Hollow Bastion / Radiant Garden', 'Cavern of Remembrance: Mining Area', 'Serenity Crystal'),
                 ('Hollow Bastion / Radiant Garden', 'Cavern of Remembrance: Mining Area', 'Manifest Illusion'),
                 ('Hollow Bastion / Radiant Garden', 'Cavern of Remembrance: Mining Area', 'Serenity Gem'),
                 ('Hollow Bastion / Radiant Garden', 'Cavern of Remembrance: Mining Area', 'Dark Remembrance Map'),
                 ('Hollow Bastion / Radiant Garden', 'Cavern of Remembrance: Engine Chamber', 'Serenity Crystal'),
                 ('Hollow Bastion / Radiant Garden', 'Cavern of Remembrance: Engine Chamber', 'Remembrance Crystal'),
                 ('Hollow Bastion / Radiant Garden', 'Cavern of Remembrance: Engine Chamber', 'AP Boost'),
                 ('Hollow Bastion / Radiant Garden', 'Cavern of Remembrance: Engine Chamber', 'Manifest Illusion'),
                 ('Hollow Bastion / Radiant Garden', 'Cavern of Remembrance: Mineshaft', 'AP Boost'),
                 ('Hollow Bastion / Radiant Garden', 'Cavern of Remembrance: Mineshaft', 'AP Boost'),
                 ('Hollow Bastion / Radiant Garden', 'Cavern of Remembrance: Mineshaft', 'Depths of Remembrance Map'),
                 ('Hollow Bastion / Radiant Garden', 'Cavern of Remembrance: Mineshaft', 'Power Boost'),
                 ('Hollow Bastion / Radiant Garden', 'Cavern of Remembrance: Mineshaft', 'Magic Boost'),
                 ('Hollow Bastion / Radiant Garden', 'Cavern of Remembrance: Garden of Assemblage', 'Garden of Assemblage Map'),
                 ('Hollow Bastion / Radiant Garden', 'Cavern of Remembrance: Garden of Assemblage', 'Lost Illusion'),
                 ('Hollow Bastion / Radiant Garden', 'Cavern of Remembrance: Garden of Assemblage', 'Non-Existent Proof'),
                 ('Beast''s Castle', 'Courtyard', 'AP Boost'),
                 ('Beast''s Castle', 'Courtyard', 'Hi-Potion'),
                 ('Beast''s Castle', 'Courtyard', 'Mythril Shard'),
                 ('Beast''s Castle', 'Belle''s Room', 'Castle Map'),
                 ('Beast''s Castle', 'Belle''s Room', 'Mega Recipe'),
                 ('Beast''s Castle', 'East Wing', 'Mythril Shard'),
                 ('Beast''s Castle', 'East Wing', 'Tent'),
                 ('Beast''s Castle', 'West Hall', 'Hi-Potion'),
                 ('Beast''s Castle', 'West Hall', 'Mythril Shard'),
                 ('Beast''s Castle', 'West Hall', 'Power Shard'),
                 ('Beast''s Castle', 'West Hall', 'Mythril Shard'),
                 ('Beast''s Castle', 'West Hall', 'AP Boost'),
                 ('Beast''s Castle', 'West Hall', 'Bright Stone'),
                 ('Beast''s Castle', 'Dungeon', 'Basement Map'),
                 ('Beast''s Castle', 'Dungeon', 'AP Boost'),
                 ('Beast''s Castle', 'Secret Passage', 'Mythril Shard'),
                 ('Beast''s Castle', 'Secret Passage', 'Hi-Potion'),
                 ('Beast''s Castle', 'Secret Passage', 'Lucid Shard'),
                 ('Beast''s Castle', 'West Wing', 'Mythril Shard'),
                 ('Beast''s Castle', 'West Wing', 'Tent'),
                 ('Beast''s Castle', 'Beast''s Room', 'Blazing Shard'),
                 ('Olympus Coliseum', 'Underworld Entrance', 'Power Boost'),
                 ('Olympus Coliseum', 'Cave of the Dead: Passage', 'Mythril Shard'),
                 ('Olympus Coliseum', 'Cave of the Dead: Passage', 'Mythril Stone'),
                 ('Olympus Coliseum', 'Cave of the Dead: Passage', 'Ether'),
                 ('Olympus Coliseum', 'Cave of the Dead: Passage', 'AP Boost'),
                 ('Olympus Coliseum', 'Cave of the Dead: Passage', 'Hi-Potion'),
                 ('Olympus Coliseum', 'Cave of the Dead: Inner Chamber', 'Underworld Map'),
                 ('Olympus Coliseum', 'Cave of the Dead: Inner Chamber', 'Mythril Shard'),
                 ('Olympus Coliseum', 'Underworld Cavern: Entrance', 'Lucid Shard'),
                 ('Olympus Coliseum', 'Underworld Cavern: Entrance', 'AP Boost'),
                 ('Olympus Coliseum', 'Underworld Cavern: Entrance', 'Mythril Shard'),
                 ('Olympus Coliseum', 'Underworld Cavern: The Lost Road', 'Bright Shard'),
                 ('Olympus Coliseum', 'Underworld Cavern: The Lost Road', 'Ether'),
                 ('Olympus Coliseum', 'Underworld Cavern: The Lost Road', 'Mythril Shard'),
                 ('Olympus Coliseum', 'Underworld Cavern: The Lost Road', 'Mythril Stone'),
                 ('Olympus Coliseum', 'Underworld Cavern: Atrium', 'Lucid Stone'),
                 ('Olympus Coliseum', 'Underworld Cavern: Atrium', 'AP Boost'),
                 ('Olympus Coliseum', 'The Lock', 'Caverns Map'),
                 ('Olympus Coliseum', 'The Lock', 'Mythril Shard'),
                 ('Olympus Coliseum', 'The Lock', 'AP Boost'),
                 ('Agrabah', 'Agrabah', 'Dark Shard'),
                 ('Agrabah', 'Agrabah', 'Mythril Shard'),
                 ('Agrabah', 'Agrabah', 'Hi-Potion'),
                 ('Agrabah', 'Agrabah', 'AP Boost'),
                 ('Agrabah', 'Agrabah', 'Mythril Stone'),
                 ('Agrabah', 'Agrabah', 'Mythril Shard'),
                 ('Agrabah', 'Agrabah', 'Serenity Shard'),
                 ('Agrabah', 'Bazaar', 'Mythril Gem'),
                 ('Agrabah', 'Bazaar', 'Power Shard'),
                 ('Agrabah', 'Bazaar', 'Hi-Potion'),
                 ('Agrabah', 'Bazaar', 'AP Boost'),
                 ('Agrabah', 'Bazaar', 'Mythril Shard'),
                 ('Agrabah', 'Palace Walls', 'Skill Ring'),
                 ('Agrabah', 'Palace Walls', 'Mythril Stone'),
                 ('Agrabah', 'Cave of Wonders: Entrance', 'Power Stone'),
                 ('Agrabah', 'Cave of Wonders: Entrance', 'Mythril Shard'),
                 ('Agrabah', 'Cave of Wonders: Valley of Stone', 'Mythril Stone'),
                 ('Agrabah', 'Cave of Wonders: Valley of Stone', 'AP Boost'),
                 ('Agrabah', 'Cave of Wonders: Valley of Stone', 'Mythril Shard'),
                 ('Agrabah', 'Cave of Wonders: Valley of Stone', 'Hi-Potion'),
                 ('Agrabah', 'Cave of Wonders: Chasm of Challenges', 'Cave of Wonders Map'),
                 ('Agrabah', 'Cave of Wonders: Chasm of Challenges', 'AP Boost'),
                 ('Agrabah', 'Cave of Wonders: Treasure Room', 'AP Boost'),
                 ('Agrabah', 'Cave of Wonders: Treasure Room', 'Serenity Shard'),
                 ('Agrabah', 'Ruined Chamber', 'Torn Pages'),
                 ('Agrabah', 'Ruined Chamber', 'Ruins Map'),
                 ('The Land of Dragons', 'Bamboo Grove', 'Dark Shard'),
                 ('The Land of Dragons', 'Bamboo Grove', 'Ether'),
                 ('The Land of Dragons', 'Bamboo Grove', 'Mythril Shard'),
                 ('The Land of Dragons', 'Checkpoint', 'Hi-Potion'),
                 ('The Land of Dragons', 'Checkpoint', 'Mythril Shard'),
                 ('The Land of Dragons', 'Mountain Trail', 'Lightning Shard'),
                 ('The Land of Dragons', 'Mountain Trail', 'Recovery Recipe'),
                 ('The Land of Dragons', 'Mountain Trail', 'Ether'),
                 ('The Land of Dragons', 'Mountain Trail', 'Mythril Shard'),
                 ('The Land of Dragons', 'Village Cave', 'AP Boost'),
                 ('The Land of Dragons', 'Village Cave', 'Dark Shard'),
                 ('The Land of Dragons', 'Ridge', 'Frost Shard'),
                 ('The Land of Dragons', 'Ridge', 'AP Boost'),
                 ('The Land of Dragons', 'Throne Room', 'Torn Pages'),
                 ('The Land of Dragons', 'Throne Room', 'Palace Map'),
                 ('The Land of Dragons', 'Throne Room', 'AP Boost'),
                 ('The Land of Dragons', 'Throne Room', 'Queen Recipe'),
                 ('The Land of Dragons', 'Throne Room', 'AP Boost'),
                 ('The Land of Dragons', 'Throne Room', 'Ogre Shield'),
                 ('The Land of Dragons', 'Throne Room', 'Mythril Crystal'),
                 ('The Land of Dragons', 'Throne Room', 'Orichalcum'),
                 ('100 Acre Wood', 'Pooh Bear''s House', '100 Acre Wood Map'),
                 ('100 Acre Wood', 'Pooh Bear''s House', 'AP Boost'),
                 ('100 Acre Wood', 'Pooh Bear''s House', 'Mythril Stone'),
                 ('100 Acre Wood', 'Piglet''s House', 'Defense Boost'),
                 ('100 Acre Wood', 'Piglet''s House', 'AP Boost'),
                 ('100 Acre Wood', 'Piglet''s House', 'Mythril Gem'),
                 ('100 Acre Wood', 'Rabbit''s House', 'Draw Ring'),
                 ('100 Acre Wood', 'Rabbit''s House', 'Mythril Crystal'),
                 ('100 Acre Wood', 'Rabbit''s House', 'AP Boost'),
                 ('100 Acre Wood', 'Kanga''s House', 'Magic Boost'),
                 ('100 Acre Wood', 'Kanga''s House', 'AP Boost'),
                 ('100 Acre Wood', 'Kanga''s House', 'Orichalcum'),
                 ('100 Acre Wood', 'The Spooky Cave', 'Mythril Gem'),
                 ('100 Acre Wood', 'The Spooky Cave', 'AP Boost'),
                 ('100 Acre Wood', 'The Spooky Cave', 'Orichalcum'),
                 ('100 Acre Wood', 'The Spooky Cave', 'Guard Recipe'),
                 ('100 Acre Wood', 'The Spooky Cave', 'Mythril Crystal'),
                 ('100 Acre Wood', 'The Spooky Cave', 'AP Boost'),
                 ('100 Acre Wood', 'Starry Hill', 'Cosmic Ring'),
                 ('100 Acre Wood', 'Starry Hill', 'Style Recipe'),
                 ('Pride Lands', 'Gorge', 'Savannah Map'),
                 ('Pride Lands', 'Gorge', 'Dark Gem'),
                 ('Pride Lands', 'Gorge', 'Mythril Stone'),
                 ('Pride Lands', 'Elephant Graveyard', 'Frost Gem'),
                 ('Pride Lands', 'Elephant Graveyard', 'Mythril Stone'),
                 ('Pride Lands', 'Elephant Graveyard', 'Bright Stone'),
                 ('Pride Lands', 'Elephant Graveyard', 'AP Boost'),
                 ('Pride Lands', 'Elephant Graveyard', 'Mythril Shard'),
                 ('Pride Lands', 'Pride Rock', 'Pride Rock Map'),
                 ('Pride Lands', 'Pride Rock', 'Mythril Stone'),
                 ('Pride Lands', 'Pride Rock', 'Serenity Crystal'),
                 ('Pride Lands', 'Wildebeest Valley', 'Energy Stone'),
                 ('Pride Lands', 'Wildebeest Valley', 'AP Boost'),
                 ('Pride Lands', 'Wildebeest Valley', 'Mythril Gem'),
                 ('Pride Lands', 'Wildebeest Valley', 'Mythril Stone'),
                 ('Pride Lands', 'Wildebeest Valley', 'Lucid Gem'),
                 ('Pride Lands', 'Wastelands', 'Mythril Shard'),
                 ('Pride Lands', 'Wastelands', 'Serenity Gem'),
                 ('Pride Lands', 'Wastelands', 'Mythril Stone'),
                 ('Pride Lands', 'Jungle', 'Serenity Gem'),
                 ('Pride Lands', 'Jungle', 'Mythril Stone'),
                 ('Pride Lands', 'Jungle', 'Serenity Crystal'),
                 ('Pride Lands', 'Oasis', 'Oasis Map'),
                 ('Pride Lands', 'Oasis', 'Torn Pages'),
                 ('Pride Lands', 'Oasis', 'AP Boost'),
                 ('Disney Castle', 'Courtyard', 'Mythril Shard'),
                 ('Disney Castle', 'Courtyard', 'Star Recipe'),
                 ('Disney Castle', 'Courtyard', 'AP Boost'),
                 ('Disney Castle', 'Courtyard', 'Mythril Stone'),
                 ('Disney Castle', 'Courtyard', 'Blazing Stone'),
                 ('Disney Castle', 'Courtyard', 'Blazing Shard'),
                 ('Disney Castle', 'Courtyard', 'Mythril Shard'),
                 ('Disney Castle', 'Library', 'Torn Pages'),
                 ('Timeless River', 'Cornerstone Hill', 'Cornerstone Hill Map'),
                 ('Timeless River', 'Cornerstone Hill', 'Frost Shard'),
                 ('Timeless River', 'Pier', 'Mythril Shard'),
                 ('Timeless River', 'Pier', 'Hi-Potion'),
                 ('Timeless River', 'Waterway', 'Mythril Stone'),
                 ('Timeless River', 'Waterway', 'AP Boost'),
                 ('Timeless River', 'Waterway', 'Frost Stone'),
                 ('Halloween Town', 'Graveyard', 'Mythril Shard'),
                 ('Halloween Town', 'Graveyard', 'Serenity Gem'),
                 ('Halloween Town', 'Dr. Finkelstein''s Lab', 'Halloween Town Map'),
                 ('Halloween Town', 'Town Square', 'Mythril Stone'),
                 ('Halloween Town', 'Town Square', 'Energy Shard'),
                 ('Halloween Town', 'Hinterlands', 'Lightning Shard'),
                 ('Halloween Town', 'Hinterlands', 'Mythril Stone'),
                 ('Halloween Town', 'Hinterlands', 'AP Boost'),
                 ('Halloween Town', 'Candy Cane Lane', 'Mega-Potion'),
                 ('Halloween Town', 'Candy Cane Lane', 'Mythril Gem'),
                 ('Halloween Town', 'Candy Cane Lane', 'Lightning Stone'),
                 ('Halloween Town', 'Candy Cane Lane', 'Mythril Stone'),
                 ('Halloween Town', 'Santa''s House', 'Christmas Town Map'),
                 ('Halloween Town', 'Santa''s House', 'AP Boost'),
                 ('Port Royal', 'Rampart', 'Naval Map'),
                 ('Port Royal', 'Rampart', 'Mythril Stone'),
                 ('Port Royal', 'Rampart', 'Dark Shard'),
                 ('Port Royal', 'Town', 'Dark Stone'),
                 ('Port Royal', 'Town', 'AP Boost'),
                 ('Port Royal', 'Town', 'Mythril Shard'),
                 ('Port Royal', 'Town', 'Mythril Gem'),
                 ('Port Royal', 'Isla de Muerta: Cave Mouth', 'Bright Shard'),
                 ('Port Royal', 'Isla de Muerta: Cave Mouth', 'Mythril Shard'),
                 ('Port Royal', 'Isla de Muerta: Powder Store', 'AP Boost'),
                 ('Port Royal', 'Isla de Muerta: Powder Store', 'AP Boost'),
                 ('Port Royal', 'Isla de Muerta: Moonlight Nook', 'Mythril Shard'),
                 ('Port Royal', 'Isla de Muerta: Moonlight Nook', 'Serenity Gem'),
                 ('Port Royal', 'Isla de Muerta: Moonlight Nook', 'Power Stone'),
                 ('Port Royal', 'Ship Graveyard: The Interceptor''s Hold', 'Feather Charm'),
                 ('Port Royal', 'Ship Graveyard: Seadrift Keep', 'AP Boost'),
                 ('Port Royal', 'Ship Graveyard: Seadrift Keep', 'Orichalcum'),
                 ('Port Royal', 'Ship Graveyard: Seadrift Keep', 'Meteor Staff'),
                 ('Port Royal', 'Ship Graveyard: Seadrift Row', 'Serenity Gem'),
                 ('Port Royal', 'Ship Graveyard: Seadrift Row', 'King Recipe'),
                 ('Port Royal', 'Ship Graveyard: Seadrift Row', 'Mythril Crystal'),
                 ('Space Paranoids', 'Pit Cell', 'Pit Cell Map'),
                 ('Space Paranoids', 'Pit Cell', 'Mythril Crystal'),
                 ('Space Paranoids', 'Canyon', 'Dark Crystal'),
                 ('Space Paranoids', 'Canyon', 'Mythril Stone'),
                 ('Space Paranoids', 'Canyon', 'Mythril Gem'),
                 ('Space Paranoids', 'Canyon', 'Frost Crystal'),
                 ('Space Paranoids', 'I/O Tower Hallway', 'Power Crystal'),
                 ('Space Paranoids', 'I/O Tower Hallway', 'AP Boost'),
                 ('Space Paranoids', 'I/O Tower Communications Room', 'I/O Tower Map'),
                 ('Space Paranoids', 'I/O Tower Communications Room', 'Gaia Belt'),
                 ('Space Paranoids', 'Central Computer Mesa', 'AP Boost'),
                 ('Space Paranoids', 'Central Computer Mesa', 'Orichalcum+'),
                 ('Space Paranoids', 'Central Computer Mesa', 'Cosmic Arts'),
                 ('Space Paranoids', 'Central Computer Mesa', 'Central Computer Core Map'),
                 ('The World That Never Was', 'Fragment Crossing', 'Mythril Stone'),
                 ('The World That Never Was', 'Fragment Crossing', 'Mythril Crystal'),
                 ('The World That Never Was', 'Fragment Crossing', 'AP Boost'),
                 ('The World That Never Was', 'Fragment Crossing', 'Orichalcum'),
                 ('The World That Never Was', 'Memory''s Skyscraper', 'Mythril Crystal'),
                 ('The World That Never Was', 'Memory''s Skyscraper', 'AP Boost'),
                 ('The World That Never Was', 'Memory''s Skyscraper', 'Mythril Stone'),
                 ('The World That Never Was', 'The Brink of Despair', 'Dark City Map'),
                 ('The World That Never Was', 'The Brink of Despair', 'Orichalcum+'),
                 ('The World That Never Was', 'Nothing''s Call', 'Mythril Gem'),
                 ('The World That Never Was', 'Nothing''s Call', 'Orichalcum'),
                 ('The World That Never Was', 'Twilight''s View', 'Cosmic Belt'),
                 ('The World That Never Was', 'Naught''s Skyway', 'Mythril Gem'),
                 ('The World That Never Was', 'Naught''s Skyway', 'Orichalcum'),
                 ('The World That Never Was', 'Naught''s Skyway', 'Mythril Crystal'),
                 ('The World That Never Was', 'Ruin and Creation''s Passage', 'Mythril Stone'),
                 ('The World That Never Was', 'Ruin and Creation''s Passage', 'AP Boost'),
                 ('The World That Never Was', 'Ruin and Creation''s Passage', 'Mythril Crystal'),
                 ('The World That Never Was', 'Ruin and Creation''s Passage', 'Orichalcum')
         )
INSERT INTO chests (location, world_id, item_id)
SELECT
    chest_data.location,
    worlds.id,
    items.id
FROM chest_data
         JOIN worlds ON worlds.name = chest_data.world_name
         JOIN items ON items.name = chest_data.item_name;