CREATE TABLE enemies
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name      VARCHAR(120) NOT NULL,
    image_url VARCHAR(500),

    CONSTRAINT pk_enemies PRIMARY KEY (id)
);

CREATE TABLE enemy_worlds
(
    enemy_id BIGINT NOT NULL,
    world_id BIGINT NOT NULL,

    CONSTRAINT pk_enemy_worlds PRIMARY KEY (enemy_id, world_id),
    CONSTRAINT fk_enemy_worlds_enemy
        FOREIGN KEY (enemy_id) REFERENCES enemies (id) ON DELETE CASCADE,
    CONSTRAINT fk_enemy_worlds_world
        FOREIGN KEY (world_id) REFERENCES worlds (id) ON DELETE CASCADE
);

CREATE TABLE enemy_drops
(
    enemy_id BIGINT NOT NULL,
    item_id  BIGINT NOT NULL,

    CONSTRAINT pk_enemy_drops PRIMARY KEY (enemy_id, item_id),
    CONSTRAINT fk_enemy_drops_enemy
        FOREIGN KEY (enemy_id) REFERENCES enemies (id) ON DELETE CASCADE,
    CONSTRAINT fk_enemy_drops_item
        FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE
);

CREATE INDEX idx_enemy_worlds_world_id ON enemy_worlds (world_id);
CREATE INDEX idx_enemy_drops_item_id ON enemy_drops (item_id);
