-- Data base:
-- Guiding Key KH2 Final Mix Heartless/Nobody guide, with normalization/corrections
-- against KHWiki where the guide contains typos or incomplete names.
--
-- Scope:
-- * Regular Heartless and Nobodies.
-- * Bosses are intentionally excluded because their "drops" are battle rewards
--   (abilities, HP increases, slots, magic, etc.), not Item entities in the current model.
-- * Mushroom XIII and Organization XIII are not included; the source itself treats them separately.
-- * image_url is left NULL until artwork is curated separately.

WITH required_items(name) AS
(
    VALUES
        ('Akashic Record'),
        ('Akashic Record+'),
        ('Blazing Crystal'),
        ('Blazing Gem'),
        ('Blazing Shard'),
        ('Blazing Stone'),
        ('Bright Crystal'),
        ('Bright Gem'),
        ('Bright Shard'),
        ('Bright Stone'),
        ('Dark Crystal'),
        ('Dark Gem'),
        ('Dark Shard'),
        ('Dark Stone'),
        ('Dense Crystal'),
        ('Dense Gem'),
        ('Dense Shard'),
        ('Dense Stone'),
        ('Energy Crystal'),
        ('Energy Gem'),
        ('Energy Shard'),
        ('Energy Stone'),
        ('Frost Crystal'),
        ('Frost Gem'),
        ('Frost Shard'),
        ('Frost Stone'),
        ('Lightning Crystal'),
        ('Lightning Gem'),
        ('Lightning Shard'),
        ('Lightning Stone'),
        ('Lucid Crystal'),
        ('Lucid Gem'),
        ('Lucid Shard'),
        ('Lucid Stone'),
        ('Nobody Guard'),
        ('Nobody Lance'),
        ('Orichalcum'),
        ('Power Crystal'),
        ('Power Gem'),
        ('Power Shard'),
        ('Power Stone'),
        ('Remembrance Crystal'),
        ('Remembrance Gem'),
        ('Remembrance Shard'),
        ('Remembrance Stone'),
        ('Serenity Crystal'),
        ('Serenity Gem'),
        ('Serenity Shard'),
        ('Serenity Stone'),
        ('Shaman''s Relic'),
        ('Shaman''s Relic+'),
        ('Twilight Crystal'),
        ('Twilight Gem'),
        ('Twilight Shard'),
        ('Twilight Stone')
)
INSERT INTO items (name, image_url)
SELECT ri.name, '/images/items/placeholder.webp'
FROM required_items ri
WHERE NOT EXISTS (
    SELECT 1
    FROM items i
    WHERE i.name = ri.name
);

-- ---------------------------------------------------------------------------
-- Enemies
-- ---------------------------------------------------------------------------

INSERT INTO enemies (name, image_url)
VALUES
    ('Shadow', NULL),
    ('Soldier', NULL),
    ('Large Body', NULL),
    ('Silver Rock', NULL),
    ('Emerald Blues', NULL),
    ('Crimson Jazz', NULL),
    ('Air Pirate', NULL),
    ('Trick Ghost', NULL),
    ('Rabid Dog', NULL),
    ('Hook Bat', NULL),
    ('Bookmaster', NULL),
    ('Minute Bomb', NULL),
    ('Hammer Frame', NULL),
    ('Bulky Vendor', NULL),
    ('Fortuneteller', NULL),
    ('Cannon Gun', NULL),
    ('Rapid Thruster', NULL),
    ('Driller Mole', NULL),
    ('Lance Soldier', NULL),
    ('Morning Star', NULL),
    ('Fiery Globe', NULL),
    ('Icy Cube', NULL),
    ('Fat Bandit', NULL),
    ('Luna Bandit', NULL),
    ('Gargoyle Knight', NULL),
    ('Gargoyle Warrior', NULL),
    ('Wight Knight', NULL),
    ('Graveyard', NULL),
    ('Toy Soldier', NULL),
    ('Aeroplane', NULL),
    ('Hot Rod', NULL),
    ('Assault Rider', NULL),
    ('Nightwalker', NULL),
    ('Bolt Tower', NULL),
    ('Magnum Loader', NULL),
    ('Strafer', NULL),
    ('Devastator', NULL),
    ('Living Bone', NULL),
    ('Shaman', NULL),
    ('Aerial Knocker', NULL),
    ('Tornado Step', NULL),
    ('Crescendo', NULL),
    ('Creeper Plant', NULL),
    ('Armored Knight', NULL),
    ('Surveillance Robot', NULL),
    ('Neoshadow', NULL),
    ('Spring Metal', NULL),
    ('Aerial Viking', NULL),
    ('Magic Phantom', NULL),
    ('Beffudler', NULL),
    ('Runemaster', NULL),
    ('Iron Hammer', NULL),
    ('Mad Ride', NULL),
    ('Camo Cannon', NULL),
    ('Reckless', NULL),
    ('Lance Warrior', NULL),
    ('Necromancer', NULL),
    ('Aerial Champ', NULL),
    ('Dusk', NULL),
    ('Creeper', NULL),
    ('Dragoon', NULL),
    ('Assassin', NULL),
    ('Samurai', NULL),
    ('Sniper', NULL),
    ('Dancer', NULL),
    ('Berserker', NULL),
    ('Gambler', NULL),
    ('Sorcerer', NULL);

-- ---------------------------------------------------------------------------
-- Enemy -> World
--
-- MIN(id) makes the migration deterministic even if an older development
-- database accidentally contains duplicate world names.
-- ---------------------------------------------------------------------------

WITH enemy_world_data(enemy_name, world_name) AS
(
    VALUES
        ('Shadow', 'Twilight Town'),
        ('Shadow', 'Hollow Bastion / Radiant Garden'),
        ('Shadow', 'The Land of Dragons'),
        ('Shadow', 'Beast''s Castle'),
        ('Shadow', 'Olympus Coliseum'),
        ('Shadow', 'Disney Castle'),
        ('Shadow', 'Timeless River'),
        ('Shadow', 'Port Royal'),
        ('Shadow', 'Agrabah'),
        ('Shadow', 'Halloween Town'),
        ('Shadow', 'Pride Lands'),
        ('Shadow', 'Space Paranoids'),
        ('Shadow', 'The World That Never Was'),
        ('Soldier', 'Twilight Town'),
        ('Soldier', 'Hollow Bastion / Radiant Garden'),
        ('Soldier', 'The Land of Dragons'),
        ('Soldier', 'Beast''s Castle'),
        ('Soldier', 'Olympus Coliseum'),
        ('Soldier', 'Disney Castle'),
        ('Soldier', 'Timeless River'),
        ('Soldier', 'Port Royal'),
        ('Soldier', 'Agrabah'),
        ('Soldier', 'Halloween Town'),
        ('Soldier', 'Pride Lands'),
        ('Soldier', 'Space Paranoids'),
        ('Large Body', 'Beast''s Castle'),
        ('Large Body', 'Olympus Coliseum'),
        ('Large Body', 'Timeless River'),
        ('Silver Rock', 'Agrabah'),
        ('Silver Rock', 'Pride Lands'),
        ('Emerald Blues', 'Agrabah'),
        ('Emerald Blues', 'Halloween Town'),
        ('Emerald Blues', 'The Land of Dragons'),
        ('Emerald Blues', 'Space Paranoids'),
        ('Crimson Jazz', 'Hollow Bastion / Radiant Garden'),
        ('Crimson Jazz', 'Beast''s Castle'),
        ('Crimson Jazz', 'Agrabah'),
        ('Crimson Jazz', 'Olympus Coliseum'),
        ('Air Pirate', 'Port Royal'),
        ('Air Pirate', 'The Land of Dragons'),
        ('Trick Ghost', 'Olympus Coliseum'),
        ('Trick Ghost', 'Halloween Town'),
        ('Rabid Dog', 'Olympus Coliseum'),
        ('Rabid Dog', 'Port Royal'),
        ('Hook Bat', 'Beast''s Castle'),
        ('Hook Bat', 'Olympus Coliseum'),
        ('Hook Bat', 'Agrabah'),
        ('Hook Bat', 'The Land of Dragons'),
        ('Bookmaster', 'Hollow Bastion / Radiant Garden'),
        ('Bookmaster', 'Space Paranoids'),
        ('Minute Bomb', 'Disney Castle'),
        ('Minute Bomb', 'Timeless River'),
        ('Minute Bomb', 'Olympus Coliseum'),
        ('Hammer Frame', 'Beast''s Castle'),
        ('Hammer Frame', 'Timeless River'),
        ('Hammer Frame', 'Port Royal'),
        ('Bulky Vendor', 'Beast''s Castle'),
        ('Bulky Vendor', 'The Land of Dragons'),
        ('Bulky Vendor', 'Olympus Coliseum'),
        ('Bulky Vendor', 'Agrabah'),
        ('Bulky Vendor', 'Halloween Town'),
        ('Fortuneteller', 'Agrabah'),
        ('Cannon Gun', 'The Land of Dragons'),
        ('Cannon Gun', 'Port Royal'),
        ('Cannon Gun', 'Space Paranoids'),
        ('Rapid Thruster', 'The Land of Dragons'),
        ('Rapid Thruster', 'Timeless River'),
        ('Rapid Thruster', 'Port Royal'),
        ('Rapid Thruster', 'Agrabah'),
        ('Rapid Thruster', 'Pride Lands'),
        ('Driller Mole', 'Olympus Coliseum'),
        ('Driller Mole', 'Halloween Town'),
        ('Lance Soldier', 'Beast''s Castle'),
        ('Lance Soldier', 'Olympus Coliseum'),
        ('Lance Soldier', 'Port Royal'),
        ('Morning Star', 'Hollow Bastion / Radiant Garden'),
        ('Morning Star', 'Beast''s Castle'),
        ('Morning Star', 'Olympus Coliseum'),
        ('Morning Star', 'Port Royal'),
        ('Fiery Globe', 'Agrabah'),
        ('Icy Cube', 'Agrabah'),
        ('Fat Bandit', 'Agrabah'),
        ('Luna Bandit', 'Agrabah'),
        ('Gargoyle Knight', 'Beast''s Castle'),
        ('Gargoyle Warrior', 'Beast''s Castle'),
        ('Wight Knight', 'Halloween Town'),
        ('Graveyard', 'Halloween Town'),
        ('Toy Soldier', 'Halloween Town'),
        ('Aeroplane', 'Timeless River'),
        ('Hot Rod', 'Timeless River'),
        ('Assault Rider', 'The Land of Dragons'),
        ('Nightwalker', 'The Land of Dragons'),
        ('Bolt Tower', 'The Land of Dragons'),
        ('Bolt Tower', 'Disney Castle'),
        ('Bolt Tower', 'Pride Lands'),
        ('Magnum Loader', 'Hollow Bastion / Radiant Garden'),
        ('Magnum Loader', 'Space Paranoids'),
        ('Strafer', 'Hollow Bastion / Radiant Garden'),
        ('Strafer', 'Space Paranoids'),
        ('Devastator', 'Hollow Bastion / Radiant Garden'),
        ('Devastator', 'Space Paranoids'),
        ('Living Bone', 'Pride Lands'),
        ('Shaman', 'Pride Lands'),
        ('Aerial Knocker', 'Pride Lands'),
        ('Tornado Step', 'Port Royal'),
        ('Tornado Step', 'Olympus Coliseum'),
        ('Crescendo', 'Olympus Coliseum'),
        ('Creeper Plant', 'Olympus Coliseum'),
        ('Creeper Plant', 'Halloween Town'),
        ('Armored Knight', 'Hollow Bastion / Radiant Garden'),
        ('Armored Knight', 'Halloween Town'),
        ('Armored Knight', 'Pride Lands'),
        ('Armored Knight', 'Beast''s Castle'),
        ('Armored Knight', 'Port Royal'),
        ('Surveillance Robot', 'Hollow Bastion / Radiant Garden'),
        ('Surveillance Robot', 'Port Royal'),
        ('Surveillance Robot', 'Space Paranoids'),
        ('Neoshadow', 'The Land of Dragons'),
        ('Neoshadow', 'Olympus Coliseum'),
        ('Neoshadow', 'Pride Lands'),
        ('Neoshadow', 'Hollow Bastion / Radiant Garden'),
        ('Neoshadow', 'Beast''s Castle'),
        ('Neoshadow', 'Port Royal'),
        ('Neoshadow', 'Agrabah'),
        ('Neoshadow', 'Halloween Town'),
        ('Spring Metal', 'Hollow Bastion / Radiant Garden'),
        ('Aerial Viking', 'Hollow Bastion / Radiant Garden'),
        ('Magic Phantom', 'Hollow Bastion / Radiant Garden'),
        ('Beffudler', 'Hollow Bastion / Radiant Garden'),
        ('Runemaster', 'Hollow Bastion / Radiant Garden'),
        ('Iron Hammer', 'Hollow Bastion / Radiant Garden'),
        ('Mad Ride', 'Hollow Bastion / Radiant Garden'),
        ('Camo Cannon', 'Hollow Bastion / Radiant Garden'),
        ('Reckless', 'Hollow Bastion / Radiant Garden'),
        ('Lance Warrior', 'Hollow Bastion / Radiant Garden'),
        ('Necromancer', 'Hollow Bastion / Radiant Garden'),
        ('Aerial Champ', 'Hollow Bastion / Radiant Garden'),
        ('Dusk', 'Twilight Town'),
        ('Dusk', 'Beast''s Castle'),
        ('Dusk', 'Olympus Coliseum'),
        ('Dusk', 'The World That Never Was'),
        ('Creeper', 'Twilight Town'),
        ('Creeper', 'Hollow Bastion / Radiant Garden'),
        ('Creeper', 'The World That Never Was'),
        ('Dragoon', 'Twilight Town'),
        ('Dragoon', 'Beast''s Castle'),
        ('Dragoon', 'The World That Never Was'),
        ('Dragoon', 'Hollow Bastion / Radiant Garden'),
        ('Assassin', 'Twilight Town'),
        ('Assassin', 'The World That Never Was'),
        ('Samurai', 'Twilight Town'),
        ('Samurai', 'Hollow Bastion / Radiant Garden'),
        ('Samurai', 'The World That Never Was'),
        ('Sniper', 'Twilight Town'),
        ('Sniper', 'The Land of Dragons'),
        ('Sniper', 'The World That Never Was'),
        ('Sniper', 'Hollow Bastion / Radiant Garden'),
        ('Dancer', 'Twilight Town'),
        ('Dancer', 'Hollow Bastion / Radiant Garden'),
        ('Dancer', 'The World That Never Was'),
        ('Berserker', 'Twilight Town'),
        ('Berserker', 'The World That Never Was'),
        ('Gambler', 'Twilight Town'),
        ('Gambler', 'Port Royal'),
        ('Gambler', 'The World That Never Was'),
        ('Sorcerer', 'The World That Never Was'),
        ('Sorcerer', 'Hollow Bastion / Radiant Garden')
),
resolved_worlds AS
(
    SELECT name, MIN(id) AS id
    FROM worlds
    GROUP BY name
)
INSERT INTO enemy_worlds (enemy_id, world_id)
SELECT e.id, w.id
FROM enemy_world_data d
JOIN enemies e
  ON e.name = d.enemy_name
JOIN resolved_worlds w
  ON w.name = d.world_name;

-- ---------------------------------------------------------------------------
-- Enemy -> Drop Item
--
-- MIN(id) likewise avoids linking to multiple duplicate Item rows by name.
-- ---------------------------------------------------------------------------

WITH enemy_drop_data(enemy_name, item_name) AS
(
    VALUES
        ('Shadow', 'Dark Shard'),
        ('Soldier', 'Dark Shard'),
        ('Soldier', 'Bright Shard'),
        ('Large Body', 'Power Shard'),
        ('Large Body', 'Serenity Shard'),
        ('Silver Rock', 'Power Stone'),
        ('Silver Rock', 'Bright Stone'),
        ('Emerald Blues', 'Lightning Stone'),
        ('Emerald Blues', 'Energy Gem'),
        ('Crimson Jazz', 'Serenity Stone'),
        ('Crimson Jazz', 'Blazing Crystal'),
        ('Air Pirate', 'Dark Crystal'),
        ('Air Pirate', 'Bright Crystal'),
        ('Trick Ghost', 'Lucid Shard'),
        ('Trick Ghost', 'Energy Stone'),
        ('Rabid Dog', 'Lucid Shard'),
        ('Rabid Dog', 'Bright Shard'),
        ('Hook Bat', 'Frost Shard'),
        ('Hook Bat', 'Bright Gem'),
        ('Bookmaster', 'Lucid Gem'),
        ('Bookmaster', 'Energy Crystal'),
        ('Bookmaster', 'Akashic Record'),
        ('Minute Bomb', 'Blazing Shard'),
        ('Minute Bomb', 'Bright Shard'),
        ('Hammer Frame', 'Blazing Shard'),
        ('Hammer Frame', 'Energy Stone'),
        ('Bulky Vendor', 'Serenity Shard'),
        ('Bulky Vendor', 'Serenity Stone'),
        ('Bulky Vendor', 'Serenity Gem'),
        ('Bulky Vendor', 'Serenity Crystal'),
        ('Bulky Vendor', 'Orichalcum'),
        ('Fortuneteller', 'Frost Gem'),
        ('Fortuneteller', 'Energy Gem'),
        ('Cannon Gun', 'Blazing Stone'),
        ('Cannon Gun', 'Bright Stone'),
        ('Rapid Thruster', 'Lightning Shard'),
        ('Driller Mole', 'Lightning Stone'),
        ('Driller Mole', 'Bright Stone'),
        ('Lance Soldier', 'Frost Shard'),
        ('Lance Soldier', 'Energy Stone'),
        ('Morning Star', 'Power Crystal'),
        ('Morning Star', 'Serenity Stone'),
        ('Fiery Globe', 'Blazing Gem'),
        ('Icy Cube', 'Frost Gem'),
        ('Fat Bandit', 'Serenity Shard'),
        ('Fat Bandit', 'Blazing Gem'),
        ('Luna Bandit', 'Power Stone'),
        ('Luna Bandit', 'Bright Stone'),
        ('Gargoyle Knight', 'Energy Shard'),
        ('Gargoyle Knight', 'Dark Gem'),
        ('Gargoyle Warrior', 'Energy Shard'),
        ('Gargoyle Warrior', 'Dark Gem'),
        ('Wight Knight', 'Lucid Stone'),
        ('Wight Knight', 'Bright Stone'),
        ('Graveyard', 'Lucid Stone'),
        ('Graveyard', 'Serenity Shard'),
        ('Toy Soldier', 'Lucid Stone'),
        ('Toy Soldier', 'Serenity Stone'),
        ('Aeroplane', 'Frost Stone'),
        ('Aeroplane', 'Bright Stone'),
        ('Hot Rod', 'Frost Stone'),
        ('Hot Rod', 'Serenity Shard'),
        ('Assault Rider', 'Dark Stone'),
        ('Assault Rider', 'Serenity Shard'),
        ('Nightwalker', 'Energy Shard'),
        ('Nightwalker', 'Dark Stone'),
        ('Bolt Tower', 'Lightning Shard'),
        ('Bolt Tower', 'Energy Shard'),
        ('Magnum Loader', 'Lucid Gem'),
        ('Magnum Loader', 'Bright Gem'),
        ('Strafer', 'Lightning Crystal'),
        ('Strafer', 'Bright Crystal'),
        ('Devastator', 'Serenity Stone'),
        ('Devastator', 'Lightning Crystal'),
        ('Living Bone', 'Serenity Stone'),
        ('Living Bone', 'Frost Crystal'),
        ('Shaman', 'Power Gem'),
        ('Shaman', 'Energy Crystal'),
        ('Shaman', 'Shaman''s Relic'),
        ('Aerial Knocker', 'Power Gem'),
        ('Aerial Knocker', 'Bright Gem'),
        ('Tornado Step', 'Blazing Stone'),
        ('Tornado Step', 'Bright Stone'),
        ('Crescendo', 'Blazing Crystal'),
        ('Crescendo', 'Bright Crystal'),
        ('Creeper Plant', 'Power Shard'),
        ('Creeper Plant', 'Bright Shard'),
        ('Armored Knight', 'Lightning Gem'),
        ('Surveillance Robot', 'Lightning Gem'),
        ('Surveillance Robot', 'Bright Gem'),
        ('Neoshadow', 'Lucid Crystal'),
        ('Neoshadow', 'Bright Crystal'),
        ('Spring Metal', 'Serenity Gem'),
        ('Spring Metal', 'Remembrance Gem'),
        ('Aerial Viking', 'Serenity Stone'),
        ('Aerial Viking', 'Remembrance Stone'),
        ('Magic Phantom', 'Serenity Stone'),
        ('Magic Phantom', 'Remembrance Stone'),
        ('Beffudler', 'Serenity Shard'),
        ('Beffudler', 'Remembrance Shard'),
        ('Runemaster', 'Serenity Gem'),
        ('Runemaster', 'Remembrance Gem'),
        ('Runemaster', 'Akashic Record+'),
        ('Iron Hammer', 'Serenity Shard'),
        ('Iron Hammer', 'Remembrance Shard'),
        ('Mad Ride', 'Serenity Gem'),
        ('Mad Ride', 'Remembrance Gem'),
        ('Camo Cannon', 'Serenity Shard'),
        ('Camo Cannon', 'Remembrance Shard'),
        ('Reckless', 'Serenity Gem'),
        ('Reckless', 'Remembrance Crystal'),
        ('Lance Warrior', 'Serenity Stone'),
        ('Lance Warrior', 'Remembrance Stone'),
        ('Necromancer', 'Serenity Stone'),
        ('Necromancer', 'Remembrance Stone'),
        ('Necromancer', 'Shaman''s Relic+'),
        ('Aerial Champ', 'Serenity Stone'),
        ('Aerial Champ', 'Remembrance Stone'),
        ('Dusk', 'Twilight Shard'),
        ('Creeper', 'Dense Shard'),
        ('Dragoon', 'Dense Shard'),
        ('Dragoon', 'Nobody Lance'),
        ('Assassin', 'Twilight Gem'),
        ('Samurai', 'Dense Gem'),
        ('Sniper', 'Dense Stone'),
        ('Dancer', 'Twilight Stone'),
        ('Berserker', 'Dense Crystal'),
        ('Gambler', 'Twilight Shard'),
        ('Gambler', 'Nobody Guard'),
        ('Sorcerer', 'Twilight Crystal')
),
resolved_items AS
(
    SELECT name, MIN(id) AS id
    FROM items
    GROUP BY name
)
INSERT INTO enemy_drops (enemy_id, item_id)
SELECT e.id, i.id
FROM enemy_drop_data d
JOIN enemies e
  ON e.name = d.enemy_name
JOIN resolved_items i
  ON i.name = d.item_name;
